### ISSUE TITLE
Voting spec?

### ISSUE THREAD

**Issue by rueberger** [bsc-networks/workshift-website#29]
Couldn't find anything searching around the repo. Are VOCs (votes of confidence) being implemented, as they are in the old website? If so, what methods are used to choose house released compensation from votes?

**Comment by nherson** [comment]
The team didn't have time to get to that feature.  Currently, this app is only concerned with workshift.

**Comment by mitar** [comment]
I think VOCs should be a separate project. There are also other ways of doing it (Google Forms). Maybe we should share the user accounts or something, but I would say for now let's keep this just a workshift.
