### ISSUE TITLE
Support multiple units

### ISSUE THREAD

**Issue by mitar** [bsc-networks/workshift-website#41]
We should add support for multiple units (I am naming them units, not houses, so that it can easier be reused by non-BSC users).

**Comment by mlequeux** [comment]
I added a unit management tab for the superadmin user. Since I do not want to take down the website :+1:, I pushed my code to a new branch https://github.com/bsc-networks/workshift-website/tree/feature/units

**Comment by mitar** [comment]
That is good. :-)

You can also just open a pull request immediately, and then we can see the progress there. It updates as you add more commits to the branch.

**Comment by mlequeux** [comment]
Pull request opened : #64 
I just saw the travis.ci error, I will fix it asap !

**Comment by brianashpugh** [comment]
Hello, making design decisions wrt transferring workshifters between units. I assume this will be seldom used (once per semester per person at most).

I'm planning to unassign all workshifts and wipe preferences upon transfer.  Workshifts tend to be different enough between units that transferring them would be confusing. Categories will be different between units so transferring preferences would be messy or some new 'past preferences.' Doesn't seem vital to me.

**Comment by mitar** [comment]
I agree.

**Comment by brianashpugh** [comment]
That's done. Next is for Admin to have a roster for members of all units for testing convenience. Currently it can only see members of its house.

qs: For the finished product, how should the admin function? How does it work on the current workshift site?

**Comment by mitar** [comment]
We should have site-level admin and unit-level admins.

For questions current site ask Matt, workshift manager.

**Comment by brianashpugh** [comment]
agreed. How about this:

Site-level admin: creates, removes units. Can transfer users between all units. Can change anyone's status, view members of any unit.

Workshift Manager: can transfer users out of unit. Can grant unit-level admin or workshift manager status. Can create, edit, assign workshifts, set unit categories.

Unit-level admin: can transfer users out of unit. Can grant unit-level admin or workshift manager status.

This makes the unit-level admin optional, which is nice.

**Comment by mitar** [comment]
Yea. I like it.

**Comment by brianashpugh** [comment]
Pull request is merged.
