### ISSUE TITLE
Broken schedule

### ISSUE THREAD

**Issue by julienfortin** [bsc-networks/workshift-website#45]
The schedule section doesn't change even if there is a assigned workshift.

![screen shot 2015-06-30 at 2 06 35 am](https://cloud.githubusercontent.com/assets/1872075/8427498/b0cfc74a-1ecc-11e5-83df-d0f39cdcd9fe.png)

**Comment by post-l** [comment]
Schedule is suppose to be your available hours not your assigned workshifts but we can add this feature.
