### ISSUE TITLE
How to get an e-mail to an admin on "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by mitar** [bsc-networks/workshift-website#51]
So when something does not work, user gets "We're sorry, but something went wrong." page. Is there a way to also send an e-mail to a site admin when that happens? With debugging info? At least I am used to that in Django. Or is there some other way in Ruby to access all such incidents?

**Comment by mlequeux** [comment]
I'd go with http://smartinez87.github.io/exception_notification/, but since production.rb is mounted from the container, you'll need to put this in production.rb, : 

```ruby
Rails.application.config.middleware.use ExceptionNotification::Rack,
  :email => {
    :email_prefix         => "[PREFIX] ",
    :sender_address       => %{"notifier" <notifier@example.com>},
    :exception_recipients => %w{exceptions@example.com},
    :delivery_method => :smtp,
    :smtp_settings => {
      :user_name => "bob",
      :password => "password",
    }
  }
```

you can also revert production.rb to not display any debug.

**Comment by mitar** [comment]
Do I have to install anything?

Are SMTP settings necessary, they cannot be reused from the other section? So I have to supply them again?

What is `w` in `%w`? Why `sender_address` does not have one?

**Comment by mitar** [comment]
I configured the file, you should be getting e-mails as well. Do we have to wait for Docker image update? Can you test it if it works?

**Comment by mitar** [comment]
It seems it works.
