### ISSUE TITLE
Check verifier's password when checkoff

### ISSUE THREAD

**Issue by julienfortin** [bsc-networks/workshift-website#57]
Make sure that the password of the verifier is checked when checkoff.

**Comment by julienfortin** [comment]
Done, I am about to commit the code

**Comment by mitar** [comment]
Hm, what exactly is this? Is this that even if you are signed in, you have to still enter the password? Like it is in the current workshift website?

I think this is not a good UX. Imagine that on the mobile device you have to enter your password every time you want to sign off.

What I would do is instead have this be a simple sign-off as it was before, and then have a special "quick sign-off" page where user does not have to be logged in at all to sign off people. So then we would have that page open in the kitchen.

But if you log in into the system, then you are in and you do not have to reenter passwords again.

What do you think?

(I am reopening this to discuss.)

**Comment by julienfortin** [comment]
I think that the title plus the description are pretty accurate to explain the issue. On the original version you could checkoff workshift without asking a verifier (without using the verifier password to confirm the checkoff).

Now only the verifier (not the work shifter) has to enter his password.

Making a sign off page is a new issue, it's even a "feature" since it wasn't design this way on this workshift website. 

I hope this make sense

**Comment by julienfortin** [comment]
The discussion should continue there: https://github.com/bsc-networks/workshift-website/issues/66
