### ISSUE TITLE
Check date/time when selling workshifts

### ISSUE THREAD

**Issue by mwaliman** [bsc-networks/workshift-website#60]
check that a member sells a shift >= x hours before the date/time of workshift
make the choice of x only available to managers

**Comment by mwaliman** [comment]
If the member sells a workshift < x hrs before the date/time of workshift, the system should still allow them to do so, but an popup should appear that lets them know that if no on buys the workshift, they will still get blown hours. Also, some sort of marker on such cases for these sold shifts for the workshift would also be very useful.

**Comment by julienfortin** [comment]
I added this two commits which resolve most the issue. I just need to differentiate the late shifts on the market. I will do that later I am going to bed now :)

**Comment by julienfortin** [comment]
I will fix the travis build asap.
